---
version: '3.1'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=warehouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 5

  liquibase:
    depends_on: 
      - postgres
    image: liquibase/liquibase:latest
    command: --url="jdbc:postgresql://postgres:5432/warehouse?user=postgres&password=password" --changelog-file="./changelog/changelog.yaml" update
    volumes:
      - ./migrations/config/:/liquibase/changelog/