name:                servant-blog
version:             0.1.0.0
github:              "carlota-moh/servant-blog"
license:             BSD-3-Clause
author:              "Carlota Monedero"
maintainer:          "carlota.monederoh@gmail.com"
copyright:           "2024 Carlota Monedero"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/carlota-moh/servant-blog#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- http-client
- postgresql-simple
- servant
- servant-client
- servant-server
- text
- time
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  servant-blog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-blog

tests:
  servant-blog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-blog
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
